/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProRouteImport } from './routes/pro'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ProProfileRouteImport } from './routes/pro.profile'
import { Route as ProOnboardingRouteImport } from './routes/pro.onboarding'
import { Route as ProNotificationsRouteImport } from './routes/pro.notifications'
import { Route as ProEarningsRouteImport } from './routes/pro.earnings'
import { Route as ProDocumentsRouteImport } from './routes/pro.documents'
import { Route as ProBookingsRouteImport } from './routes/pro.bookings'
import { Route as ProAvailabilityRouteImport } from './routes/pro.availability'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as ContentKeyRouteImport } from './routes/content.$key'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as BookProviderIdRouteImport } from './routes/book.$providerId'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AddressesNewRouteImport } from './routes/addresses.new'
import { Route as AddressesIdRouteImport } from './routes/addresses.$id'
import { Route as ProBookingIdRouteImport } from './routes/pro.booking.$id'
import { Route as AdminProviderIdRouteImport } from './routes/admin.provider.$id'
import { Route as AdminCustomerIdRouteImport } from './routes/admin.customer.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProProfileRoute = ProProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProRoute,
} as any)
const ProOnboardingRoute = ProOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProRoute,
} as any)
const ProNotificationsRoute = ProNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProRoute,
} as any)
const ProEarningsRoute = ProEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => ProRoute,
} as any)
const ProDocumentsRoute = ProDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProRoute,
} as any)
const ProBookingsRoute = ProBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ProRoute,
} as any)
const ProAvailabilityRoute = ProAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => ProRoute,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const ContentKeyRoute = ContentKeyRouteImport.update({
  id: '/content/$key',
  path: '/content/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookProviderIdRoute = BookProviderIdRouteImport.update({
  id: '/book/$providerId',
  path: '/book/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AddressesNewRoute = AddressesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AddressesRoute,
} as any)
const AddressesIdRoute = AddressesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AddressesRoute,
} as any)
const ProBookingIdRoute = ProBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => ProRoute,
} as any)
const AdminProviderIdRoute = AdminProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerIdRoute = AdminCustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/pro': typeof ProRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/addresses/$id': typeof AddressesIdRoute
  '/addresses/new': typeof AddressesNewRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/category/$id': typeof CategoryIdRoute
  '/content/$key': typeof ContentKeyRoute
  '/messages/$id': typeof MessagesIdRoute
  '/pro/availability': typeof ProAvailabilityRoute
  '/pro/bookings': typeof ProBookingsRoute
  '/pro/documents': typeof ProDocumentsRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/onboarding': typeof ProOnboardingRoute
  '/pro/profile': typeof ProProfileRoute
  '/provider/$id': typeof ProviderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/pro/': typeof ProIndexRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/admin/provider/$id': typeof AdminProviderIdRoute
  '/pro/booking/$id': typeof ProBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/addresses/$id': typeof AddressesIdRoute
  '/addresses/new': typeof AddressesNewRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/category/$id': typeof CategoryIdRoute
  '/content/$key': typeof ContentKeyRoute
  '/messages/$id': typeof MessagesIdRoute
  '/pro/availability': typeof ProAvailabilityRoute
  '/pro/bookings': typeof ProBookingsRoute
  '/pro/documents': typeof ProDocumentsRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/onboarding': typeof ProOnboardingRoute
  '/pro/profile': typeof ProProfileRoute
  '/provider/$id': typeof ProviderIdRoute
  '/admin': typeof AdminIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/pro': typeof ProIndexRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/admin/provider/$id': typeof AdminProviderIdRoute
  '/pro/booking/$id': typeof ProBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/pro': typeof ProRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/addresses/$id': typeof AddressesIdRoute
  '/addresses/new': typeof AddressesNewRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/book/$providerId': typeof BookProviderIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/category/$id': typeof CategoryIdRoute
  '/content/$key': typeof ContentKeyRoute
  '/messages/$id': typeof MessagesIdRoute
  '/pro/availability': typeof ProAvailabilityRoute
  '/pro/bookings': typeof ProBookingsRoute
  '/pro/documents': typeof ProDocumentsRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/notifications': typeof ProNotificationsRoute
  '/pro/onboarding': typeof ProOnboardingRoute
  '/pro/profile': typeof ProProfileRoute
  '/provider/$id': typeof ProviderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/pro/': typeof ProIndexRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/admin/provider/$id': typeof AdminProviderIdRoute
  '/pro/booking/$id': typeof ProBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/admin'
    | '/bookings'
    | '/favorites'
    | '/help'
    | '/home'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/pro'
    | '/profile'
    | '/search'
    | '/setup'
    | '/addresses/$id'
    | '/addresses/new'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/zones'
    | '/auth/forgot'
    | '/auth/set-password'
    | '/book/$providerId'
    | '/booking/$id'
    | '/category/$id'
    | '/content/$key'
    | '/messages/$id'
    | '/pro/availability'
    | '/pro/bookings'
    | '/pro/documents'
    | '/pro/earnings'
    | '/pro/notifications'
    | '/pro/onboarding'
    | '/pro/profile'
    | '/provider/$id'
    | '/admin/'
    | '/messages/'
    | '/pro/'
    | '/admin/customer/$id'
    | '/admin/provider/$id'
    | '/pro/booking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/bookings'
    | '/favorites'
    | '/help'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/profile'
    | '/search'
    | '/setup'
    | '/addresses/$id'
    | '/addresses/new'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/zones'
    | '/auth/forgot'
    | '/auth/set-password'
    | '/book/$providerId'
    | '/booking/$id'
    | '/category/$id'
    | '/content/$key'
    | '/messages/$id'
    | '/pro/availability'
    | '/pro/bookings'
    | '/pro/documents'
    | '/pro/earnings'
    | '/pro/notifications'
    | '/pro/onboarding'
    | '/pro/profile'
    | '/provider/$id'
    | '/admin'
    | '/messages'
    | '/pro'
    | '/admin/customer/$id'
    | '/admin/provider/$id'
    | '/pro/booking/$id'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/admin'
    | '/bookings'
    | '/favorites'
    | '/help'
    | '/home'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/pro'
    | '/profile'
    | '/search'
    | '/setup'
    | '/addresses/$id'
    | '/addresses/new'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/payment-methods'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/zones'
    | '/auth/forgot'
    | '/auth/set-password'
    | '/book/$providerId'
    | '/booking/$id'
    | '/category/$id'
    | '/content/$key'
    | '/messages/$id'
    | '/pro/availability'
    | '/pro/bookings'
    | '/pro/documents'
    | '/pro/earnings'
    | '/pro/notifications'
    | '/pro/onboarding'
    | '/pro/profile'
    | '/provider/$id'
    | '/admin/'
    | '/messages/'
    | '/pro/'
    | '/admin/customer/$id'
    | '/admin/provider/$id'
    | '/pro/booking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  ProRoute: typeof ProRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  BookProviderIdRoute: typeof BookProviderIdRoute
  BookingIdRoute: typeof BookingIdRoute
  CategoryIdRoute: typeof CategoryIdRoute
  ContentKeyRoute: typeof ContentKeyRoute
  ProviderIdRoute: typeof ProviderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/profile': {
      id: '/pro/profile'
      path: '/profile'
      fullPath: '/pro/profile'
      preLoaderRoute: typeof ProProfileRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/onboarding': {
      id: '/pro/onboarding'
      path: '/onboarding'
      fullPath: '/pro/onboarding'
      preLoaderRoute: typeof ProOnboardingRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/notifications': {
      id: '/pro/notifications'
      path: '/notifications'
      fullPath: '/pro/notifications'
      preLoaderRoute: typeof ProNotificationsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/earnings': {
      id: '/pro/earnings'
      path: '/earnings'
      fullPath: '/pro/earnings'
      preLoaderRoute: typeof ProEarningsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/documents': {
      id: '/pro/documents'
      path: '/documents'
      fullPath: '/pro/documents'
      preLoaderRoute: typeof ProDocumentsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/bookings': {
      id: '/pro/bookings'
      path: '/bookings'
      fullPath: '/pro/bookings'
      preLoaderRoute: typeof ProBookingsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/availability': {
      id: '/pro/availability'
      path: '/availability'
      fullPath: '/pro/availability'
      preLoaderRoute: typeof ProAvailabilityRouteImport
      parentRoute: typeof ProRoute
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/content/$key': {
      id: '/content/$key'
      path: '/content/$key'
      fullPath: '/content/$key'
      preLoaderRoute: typeof ContentKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$providerId': {
      id: '/book/$providerId'
      path: '/book/$providerId'
      fullPath: '/book/$providerId'
      preLoaderRoute: typeof BookProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/addresses/new': {
      id: '/addresses/new'
      path: '/new'
      fullPath: '/addresses/new'
      preLoaderRoute: typeof AddressesNewRouteImport
      parentRoute: typeof AddressesRoute
    }
    '/addresses/$id': {
      id: '/addresses/$id'
      path: '/$id'
      fullPath: '/addresses/$id'
      preLoaderRoute: typeof AddressesIdRouteImport
      parentRoute: typeof AddressesRoute
    }
    '/pro/booking/$id': {
      id: '/pro/booking/$id'
      path: '/booking/$id'
      fullPath: '/pro/booking/$id'
      preLoaderRoute: typeof ProBookingIdRouteImport
      parentRoute: typeof ProRoute
    }
    '/admin/provider/$id': {
      id: '/admin/provider/$id'
      path: '/provider/$id'
      fullPath: '/admin/provider/$id'
      preLoaderRoute: typeof AdminProviderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer/$id': {
      id: '/admin/customer/$id'
      path: '/customer/$id'
      fullPath: '/admin/customer/$id'
      preLoaderRoute: typeof AdminCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AddressesRouteChildren {
  AddressesIdRoute: typeof AddressesIdRoute
  AddressesNewRoute: typeof AddressesNewRoute
}

const AddressesRouteChildren: AddressesRouteChildren = {
  AddressesIdRoute: AddressesIdRoute,
  AddressesNewRoute: AddressesNewRoute,
}

const AddressesRouteWithChildren = AddressesRoute._addFileChildren(
  AddressesRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomerIdRoute: typeof AdminCustomerIdRoute
  AdminProviderIdRoute: typeof AdminProviderIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomerIdRoute: AdminCustomerIdRoute,
  AdminProviderIdRoute: AdminProviderIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface ProRouteChildren {
  ProAvailabilityRoute: typeof ProAvailabilityRoute
  ProBookingsRoute: typeof ProBookingsRoute
  ProDocumentsRoute: typeof ProDocumentsRoute
  ProEarningsRoute: typeof ProEarningsRoute
  ProNotificationsRoute: typeof ProNotificationsRoute
  ProOnboardingRoute: typeof ProOnboardingRoute
  ProProfileRoute: typeof ProProfileRoute
  ProIndexRoute: typeof ProIndexRoute
  ProBookingIdRoute: typeof ProBookingIdRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProAvailabilityRoute: ProAvailabilityRoute,
  ProBookingsRoute: ProBookingsRoute,
  ProDocumentsRoute: ProDocumentsRoute,
  ProEarningsRoute: ProEarningsRoute,
  ProNotificationsRoute: ProNotificationsRoute,
  ProOnboardingRoute: ProOnboardingRoute,
  ProProfileRoute: ProProfileRoute,
  ProIndexRoute: ProIndexRoute,
  ProBookingIdRoute: ProBookingIdRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  ProRoute: ProRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  BookProviderIdRoute: BookProviderIdRoute,
  BookingIdRoute: BookingIdRoute,
  CategoryIdRoute: CategoryIdRoute,
  ContentKeyRoute: ContentKeyRoute,
  ProviderIdRoute: ProviderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
